// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class AppUser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string NormalizedUserName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public Guid? SecurityStamp { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public virtual ICollection<Mark> Marks { get; set; } = new List<Mark>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual Student Student { get; set; }

    public virtual ICollection<TeacherSection> TeacherSections { get; set; } = new List<TeacherSection>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}