// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Class
{
    public int ClassId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public virtual ICollection<Section> Sections { get; set; } = new List<Section>();
}