// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Exam
{
    public int ExamId { get; set; }

    public string ExamType { get; set; }

    public string DisplayName { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public virtual ICollection<Mark> Marks { get; set; } = new List<Mark>();

    public virtual ICollection<RankingSnapshot> RankingSnapshots { get; set; } = new List<RankingSnapshot>();
}