// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class JobAttemptLog
{
    public long AttemptId { get; set; }

    public long JobId { get; set; }

    public int AttemptNumber { get; set; }

    public DateTime? AtUtc { get; set; }

    public string Outcome { get; set; }

    public virtual MarkProcessingJob Job { get; set; }
}