// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class MarkProcessingJob
{
    public long JobId { get; set; }

    public string IdempotencyKey { get; set; }

    public string Status { get; set; }

    public string PayloadJson { get; set; }

    public int? RetryCount { get; set; }

    public int? MaxRetries { get; set; }

    public DateTime? NextAttemptAtUtc { get; set; }

    public DateTime? LockedUntilUtc { get; set; }

    public string LastError { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public virtual ICollection<JobAttemptLog> JobAttemptLogs { get; set; } = new List<JobAttemptLog>();
}