// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Mark
{
    public long MarkId { get; set; }

    public int StudentId { get; set; }

    public int SubjectId { get; set; }

    public int ExamId { get; set; }

    public decimal? Score { get; set; }

    public int? EnteredByUserId { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual AppUser EnteredByUser { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Student Student { get; set; }

    public virtual Subject Subject { get; set; }
}