// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class RankingSnapshot
{
    public long SnapshotId { get; set; }

    public int ExamId { get; set; }

    public string Scope { get; set; }

    public int ScopeId { get; set; }

    public DateTime? ComputedAtUtc { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<RankingRow> RankingRows { get; set; } = new List<RankingRow>();
}