// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class RankingRow
{
    public long RankingRowId { get; set; }

    public long SnapshotId { get; set; }

    public int StudentId { get; set; }

    public decimal TotalScore { get; set; }

    public int Rank { get; set; }

    public int? TieSize { get; set; }

    public virtual RankingSnapshot Snapshot { get; set; }

    public virtual Student Student { get; set; }
}