// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Role
{
    public byte RoleId { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<AppUser> Users { get; set; } = new List<AppUser>();
}