// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SchoolApplication.Models;

public partial class SchoolAssessmentContext : DbContext
{
    public SchoolAssessmentContext(DbContextOptions<SchoolAssessmentContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<JobAttemptLog> JobAttemptLogs { get; set; }

    public virtual DbSet<Mark> Marks { get; set; }

    public virtual DbSet<MarkProcessingJob> MarkProcessingJobs { get; set; }

    public virtual DbSet<RankingRow> RankingRows { get; set; }

    public virtual DbSet<RankingSnapshot> RankingSnapshots { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Section> Sections { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<TeacherSection> TeacherSections { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__AppUsers__1788CC4C1D1A944E");

            entity.ToTable("AppUsers", "auth");

            entity.HasIndex(e => e.NormalizedUserName, "UQ__AppUsers__54E8BE228175B703").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ__AppUsers__C9F284564B38C34D").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.NormalizedUserName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.SecurityStamp).HasDefaultValueSql("(newid())");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "UserRole",
                    r => r.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__UserRoles__RoleI__5535A963"),
                    l => l.HasOne<AppUser>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__UserRoles__UserI__5441852A"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId").HasName("PK__UserRole__AF2760AD19C6BB6B");
                        j.ToTable("UserRoles", "auth");
                    });
        });

        modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.ClassId).HasName("PK__Classes__CB1927C038DD9E39");

            entity.ToTable("Classes", "core");

            entity.HasIndex(e => e.Name, "UQ__Classes__737584F67ACD64D3").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.ExamId).HasName("PK__Exams__297521C77A7CEC5B");

            entity.ToTable("Exams", "core");

            entity.HasIndex(e => e.ExamType, "UQ__Exams__185694536D4FEFDA").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ExamType)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<JobAttemptLog>(entity =>
        {
            entity.HasKey(e => e.AttemptId).HasName("PK__JobAttem__891A68E62FAD58B5");

            entity.ToTable("JobAttemptLogs", "job");

            entity.Property(e => e.AtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Outcome)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.Job).WithMany(p => p.JobAttemptLogs)
                .HasForeignKey(d => d.JobId)
                .HasConstraintName("FK__JobAttemp__JobId__0A9D95DB");
        });

        modelBuilder.Entity<Mark>(entity =>
        {
            entity.HasKey(e => e.MarkId).HasName("PK__Marks__4E30D3666103007B");

            entity.ToTable("Marks", "core");

            entity.HasIndex(e => new { e.StudentId, e.ExamId }, "IX_Marks_StudentExam");

            entity.HasIndex(e => new { e.StudentId, e.SubjectId, e.ExamId }, "UQ__Marks__6E2DE483F8DF752A").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Score).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.UpdatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.EnteredByUser).WithMany(p => p.Marks)
                .HasForeignKey(d => d.EnteredByUserId)
                .HasConstraintName("FK__Marks__EnteredBy__7E37BEF6");

            entity.HasOne(d => d.Exam).WithMany(p => p.Marks)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Marks__ExamId__7D439ABD");

            entity.HasOne(d => d.Student).WithMany(p => p.Marks)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Marks__StudentId__7B5B524B");

            entity.HasOne(d => d.Subject).WithMany(p => p.Marks)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Marks__SubjectId__7C4F7684");
        });

        modelBuilder.Entity<MarkProcessingJob>(entity =>
        {
            entity.HasKey(e => e.JobId).HasName("PK__MarkProc__056690C23BFE0C53");

            entity.ToTable("MarkProcessingJobs", "job");

            entity.HasIndex(e => e.IdempotencyKey, "UQ__MarkProc__A6D161D8254A4163").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IdempotencyKey)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastError).HasMaxLength(2000);
            entity.Property(e => e.MaxRetries).HasDefaultValue(3);
            entity.Property(e => e.NextAttemptAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PayloadJson).IsRequired();
            entity.Property(e => e.RetryCount).HasDefaultValue(0);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<RankingRow>(entity =>
        {
            entity.HasKey(e => e.RankingRowId).HasName("PK__RankingR__2642FFCCC7C16331");

            entity.ToTable("RankingRows", "rank");

            entity.HasIndex(e => new { e.SnapshotId, e.Rank }, "IX_Rank");

            entity.HasIndex(e => new { e.SnapshotId, e.StudentId }, "UQ__RankingR__E5630593B8215845").IsUnique();

            entity.Property(e => e.TieSize).HasDefaultValue(1);
            entity.Property(e => e.TotalScore).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.Snapshot).WithMany(p => p.RankingRows)
                .HasForeignKey(d => d.SnapshotId)
                .HasConstraintName("FK__RankingRo__Snaps__151B244E");

            entity.HasOne(d => d.Student).WithMany(p => p.RankingRows)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RankingRo__Stude__160F4887");
        });

        modelBuilder.Entity<RankingSnapshot>(entity =>
        {
            entity.HasKey(e => e.SnapshotId).HasName("PK__RankingS__664F572B85ACDF2D");

            entity.ToTable("RankingSnapshots", "rank");

            entity.HasIndex(e => new { e.ExamId, e.Scope, e.ScopeId }, "UQ__RankingS__D71680902DD89B70").IsUnique();

            entity.Property(e => e.ComputedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Scope)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Exam).WithMany(p => p.RankingSnapshots)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RankingSn__ExamI__10566F31");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.RefreshTokenId).HasName("PK__RefreshT__F5845E39B111935D");

            entity.ToTable("RefreshTokens", "auth");

            entity.HasIndex(e => e.TokenHash, "UQ__RefreshT__BCB33F928A2B884B").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(64);

            entity.HasOne(d => d.ReplacedBy).WithMany(p => p.InverseReplacedBy)
                .HasForeignKey(d => d.ReplacedById)
                .HasConstraintName("FK__RefreshTo__Repla__5AEE82B9");

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__RefreshTo__UserI__59FA5E80");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE1AC9622B25");

            entity.ToTable("Roles", "auth");

            entity.HasIndex(e => e.RoleName, "UQ__Roles__8A2B6160F89055AC").IsUnique();

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Section>(entity =>
        {
            entity.HasKey(e => e.SectionId).HasName("PK__Sections__80EF08729F57F9AD");

            entity.ToTable("Sections", "core");

            entity.HasIndex(e => new { e.ClassId, e.Name }, "UQ__Sections__AC2E7F8E6A516A9E").IsUnique();

            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Class).WithMany(p => p.Sections)
                .HasForeignKey(d => d.ClassId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Sections__ClassI__6383C8BA");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Students__32C52B9911EFC629");

            entity.ToTable("Students", "core");

            entity.HasIndex(e => e.UserId, "UQ__Students__1788CC4DD7CACC5C").IsUnique();

            entity.Property(e => e.AdmissionNo).HasMaxLength(50);
            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Section).WithMany(p => p.Students)
                .HasForeignKey(d => d.SectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Students__Sectio__6FE99F9F");

            entity.HasOne(d => d.User).WithOne(p => p.Student)
                .HasForeignKey<Student>(d => d.UserId)
                .HasConstraintName("FK__Students__UserId__70DDC3D8");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__AC1BA3A821209D72");

            entity.ToTable("Subjects", "core");

            entity.HasIndex(e => e.Name, "UQ__Subjects__737584F6E9F5AF32").IsUnique();

            entity.Property(e => e.Code).HasMaxLength(20);
            entity.Property(e => e.CreatedAtUtc).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<TeacherSection>(entity =>
        {
            entity.HasKey(e => new { e.TeacherUserId, e.SectionId }).HasName("PK__TeacherS__95B3E24F2775A325");

            entity.ToTable("TeacherSections", "core");

            entity.Property(e => e.AssignedAtUtc).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Section).WithMany(p => p.TeacherSections)
                .HasForeignKey(d => d.SectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherSe__Secti__75A278F5");

            entity.HasOne(d => d.TeacherUser).WithMany(p => p.TeacherSections)
                .HasForeignKey(d => d.TeacherUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherSe__Teach__74AE54BC");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}