// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Section
{
    public int SectionId { get; set; }

    public int ClassId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<TeacherSection> TeacherSections { get; set; } = new List<TeacherSection>();
}