// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public int SectionId { get; set; }

    public string FullName { get; set; }

    public string AdmissionNo { get; set; }

    public int? UserId { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public virtual ICollection<Mark> Marks { get; set; } = new List<Mark>();

    public virtual ICollection<RankingRow> RankingRows { get; set; } = new List<RankingRow>();

    public virtual Section Section { get; set; }

    public virtual AppUser User { get; set; }
}