// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class Subject
{
    public int SubjectId { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public DateTime? CreatedAtUtc { get; set; }

    public virtual ICollection<Mark> Marks { get; set; } = new List<Mark>();
}