// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolApplication.Models;

public partial class TeacherSection
{
    public int TeacherUserId { get; set; }

    public int SectionId { get; set; }

    public DateTime? AssignedAtUtc { get; set; }

    public virtual Section Section { get; set; }

    public virtual AppUser TeacherUser { get; set; }
}